import Head from "next/head";
import styles from "../styles/Home.module.css";
import About from "../components/About";
import Projects from "../components/Projects";
import Contact from "../components/Contact";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Ibnul Huq - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.hero}>
        <nav className={styles.nav}>
          <ul>
            <li className={styles.logo}>
              <a href="#">HOME</a>
            </li>
            <li className={styles.links}>
              <a href="#about">ABOUT</a>
            </li>
            <li className={styles.links}>
              <a href="#projects">PROJECTS</a>
            </li>
            <li className={styles.links}>
              <a href="#contact">CONTACT</a>
            </li>
          </ul>
        </nav>

        <div className={styles.textContainer}>
          <h1>Ibnul Huq</h1>
          <p>
            I'm an aspiring Full Stack Developer looking to get my first role in
            the industry.
          </p>
          <button className={`${styles.btn} ${styles.btnHero}`}>
            <a href="#about">More info ↓</a>
          </button>
        </div>
      </header>

      <About />

      <Projects />

      {/* <Contact /> */}
    </div>
  );
};

export default Home;
