import Head from "next/head";
import styles from "../styles/Home.module.scss";
import About from "../components/About";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import NavBar from "../components/NavBar";
import { Parallax, ParallaxLayer } from "react-spring";
import { Footer } from "../components/Footer";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Ibnul Huq - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.hero}>
        <NavBar />

        <div className={styles.textContainer}>
          <h1>Ibnul Huq</h1>
          <p>
            I am an aspiring Full Stack Developer looking to get my first role
            in the industry.
          </p>
          <button className={`${styles.btn} ${styles.btnHero}`}>
            <a href="#about">More info ↓</a>
          </button>
        </div>
      </header>

      <About />

      <Projects />

      <Contact />

      <Footer />
    </div>
  );
};

export default Home;
